# Use postgres/example user/password credentials
version: '3.9'

services:
  workspace:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile   # <- your original Dockerfile
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    user: vscode
    depends_on: [db]

  db:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - ./data:/home/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: figment_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d figment_db -h 127.0.0.1" ]
      interval: 5s
      timeout: 10s
      retries: 5
