takehome_test:
  outputs:
    dev:
      dbname: figment_db
      host: db
      pass: postgres
      port: 5432
      schema: input
      threads: 4
      type: postgres
      user: postgres
  target: dev
